server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Sert les fichiers statiques
    location /static/ {
        alias /usr/share/nginx/html/static/;
        expires 1d;
    }

    # Proxy vers le service Livres
    location /api/books {
        proxy_pass http://livres:5001/books;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy vers le service Utilisateurs
    location /api/users {
        proxy_pass http://utilisateurs:5002/users;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy vers le service Emprunts
    location /api/loans {
        proxy_pass http://emprunts:5003/loans;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy vers le service Recommandation
    location /api/recommendations/ {
        proxy_pass http://recommandation:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
}
